# Generated by Django 5.2.7 on 2025-11-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="email",
            field=models.EmailField(max_length=255),
        ),
    ]
